# Edge Functions Configuration - Updated 2026-01-09 to trigger deployment
project_id = "vewsxruqjeoehsjtgqyh"

[functions.travelapi-destination]
verify_jwt = false

[functions.travelapi-search]
verify_jwt = false

[functions.travelapi-filter-values]
verify_jwt = false

[functions.travelapi-search-poi]
verify_jwt = false

[functions.travelapi-search-geo]
verify_jwt = false

[functions.travelapi-search-ids]
verify_jwt = false

[functions.travelapi-enrich]
verify_jwt = false

[functions.worldota-hotel-info]
verify_jwt = false
